maintainer        "Gabriel Mazetto"
maintainer_email  "brodock@gmail.com"
license           "Apache 2.0"
description       "Sets up sources for ubuntu"
version           "1.0.3"
depends           "apt"
supports          "ubuntu"
recipe            "ubuntu", "Sets up sources for the node's ubuntu release"
